export const initialNursingRecord = {
  nanda: {
    domain: '',
    class: '',
    diagnosis: '',
    collectingData: '',
    goal: '',
    plan: '',
    interventions: '',
    evaluation: '',
  },
  soapie: {
    subjective: '',
    objective: '',
    assessment: '',
    planning: '',
    interventions: '',
    evaluation: '',
  },
  focusDar: { focus: '', data: '', action: '', response: '' },
  narrativeRecord: { narrativeNote: '' },
  remarks: {
    assessment: '',
    diagnosisRelate: '',
    diagnosis: '',
    goal: '',
    plan: '',
    interventions: '',
    evaluation: '',
  },
};

export const initialECardex = {
  update_at: '',
  other_remarks: '',
  remark_data: [],
  medication_data: [],
  lab_data: [],
  imaging_test_data: [],
  concerns: '',
  plans: '',
  evaluation: '',
};

export const initialTakingOver = {
  update_at: '',
  loc: '',
  vital_sign: '',
  current_condition: '',
  rbfi: '',
  reasons: '',
  intervention: '',
  other: '',
};

export const initialHospitalizationSurvey = {
  offer: '',
  update_at: '',

  contact1: [{ contact: '', name: '', relation: '', etc: '' }],
  contact2: [{ contact: '', name: '', relation: '', etc: '' }],
  contact3: [{ contact: '', name: '', relation: '', etc: '' }],

  default_info: {
    BT: '',
    DBP: '',
    PR: '',
    RR: '',
    SBP: '',
    Sp02: '',
    date: '',
    height: '',
    hospitalization_path: { value: 3, input: '' },
    hospitalization_reason: '',
    hospitalization_way: 4,
    joo_ho_so: '',
    status: 4,
    status02: 4,
    weight: '',
  },
  disease_history: {
    history: { value: 3, checked: [], input: '' },
    family_history: { value: 3, input: '' },
    allergy: { value: 3, input: '' },
    food_allergy: { value: 3, input: '' },
    latest_medicine: { value: 3, input: '' },
    medicine_allergy: { value: 3, input: '' },
    operation_history: { value: 3, input: '' },
  },
  body_status: {
    breath: { value: 3, checked: [], input: '' },
    camouflage: { value: 3, checked: [], input: '' },
    cycle: { value: 3, checked: [], input: '' },
    fain: { checked: [] },
    fall: { checked: [] },
    medicine_history: { value: 3, input: '' },
    nerve: { value: 3, checked: [], input: '' },
    operation_history: { value: 3, input: '' },
    skin: { value: 3, checked: [], input: '' },
    yukchang: { checked: [] },
  },
  habit: {
    drink: { value: 3, checked: [], input: '', input2: '' },
    feces: { value: '', input: '' },
    feces_info: { checked: [] },
    nutrition: { weight: 3, appetite: 3 },
    obstetric: { G: '', T: '', P: '', A: '', L: '' },
    sleep: 3,
    smoke: { value: 3, checked: [], input: '', input2: '' },
    urine: { value: '', input: '' },
    urine_info: { checked: [] },
  },
  functional_evaluation: {
    sit: 4,
    stand_up: 4,
    walk: 4,
    wheel_chair: 4,
  },
  social_history: {
    job: '',
    language: '한국어',
    marry: 3,
    religion: { value: 3, input: '' },
  },
  economy_history: {
    counseling: 3,
    mind_status: { checked: [] },
  },
  education: {
    education_contents: { checked: [], input: '' },
    education_way: 5,
  },
  out_hospital_plan: {
    destination: { value: 4, input: '' },
    guardian: { value: 5, input: '' },
    life: 7,
  },
};

export const initialOutHospitalSurvey = {
  date: '',
  update_at: '',
  default_info: {
    destination: { value: 5, input: '' },
    out_hospital_way: { value: 5, input: '' },
    guardians: { value: 7, input: '' },
    food: { value: 3, input: '' },
    shower: { value: 3, input: '' },
    activity: 3,
  },
  out_hospital_medicines: [
    { amount: '', count: '', days: '', how_to: '', name: '' },
    { amount: '', count: '', days: '', how_to: '', name: '' },
    { amount: '', count: '', days: '', how_to: '', name: '' },
    { amount: '', count: '', days: '', how_to: '', name: '' },
    { amount: '', count: '', days: '', how_to: '', name: '' },
  ],
  out_patients: [
    { call_number: '', date: '', department: '', doctor: '', location: '' },
    { call_number: '', date: '', department: '', doctor: '', location: '' },
  ],
  check_reservations: [
    { call_number: '', date: '', destination: '', name: '', warning: '' },
    { call_number: '', date: '', destination: '', name: '', warning: '' },
  ],
  education: '',
};

export const initialMedicationSurvey = {
  update_at: '',
  medication_surveys: [],
};

export const initialRadiology = {
  radiologies: [],
};

export const initialPathology = {
  pathologies: [],
};

export const initialClinicalObservation = {
  update_at: '',
  vital_sign: {
    // v/s 첫열
    date: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    // v/s 두번째열
    time: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    sbp: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    dbp: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    pr: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    rr: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    bt: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    spo2: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    o2: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    etc: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
  },
  weight_height: {
    height: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    weight: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
  },
  intake: {
    oral: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    veinal: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    blood_and_more: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    total: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
  },
  output: {
    urine: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    vomit: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    stool: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    drainage: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    total: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
  },
  position_change: {
    do_or_not: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    position: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
    condition: {
      No00: '',
      No01: '',
      No02: '',
      No03: '',
      No04: '',
      No05: '',
      No06: '',
      No07: '',
      No08: '',
      No09: '',
    },
  },
  restraint: {
    date: {
      restraint00: '',
      restraint10: '',
      restraint20: '',
      restraint30: '',
      restraint40: '',
      restraint50: '',
      restraint60: '',
      restraint70: '',
      restraint80: '',
      restraint90: '',
    },
    reason: {
      restraint01: '',
      restraint11: '',
      restraint21: '',
      restraint31: '',
      restraint41: '',
      restraint51: '',
      restraint61: '',
      restraint71: '',
      restraint81: '',
      restraint91: '',
    },
    part: {
      restraint02: '',
      restraint12: '',
      restraint22: '',
      restraint32: '',
      restraint42: '',
      restraint52: '',
      restraint62: '',
      restraint72: '',
      restraint82: '',
      restraint92: '',
    },
    condition: {
      restraint03: '',
      restraint13: '',
      restraint23: '',
      restraint33: '',
      restraint43: '',
      restraint53: '',
      restraint63: '',
      restraint73: '',
      restraint83: '',
      restraint93: '',
    },
    cyanosis: {
      restraint04: '',
      restraint14: '',
      restraint24: '',
      restraint34: '',
      restraint44: '',
      restraint54: '',
      restraint64: '',
      restraint74: '',
      restraint84: '',
      restraint94: '',
    },
    temp: {
      restraint05: '',
      restraint15: '',
      restraint25: '',
      restraint35: '',
      restraint45: '',
      restraint55: '',
      restraint65: '',
      restraint75: '',
      restraint85: '',
      restraint95: '',
    },
    sense: {
      restraint06: '',
      restraint16: '',
      restraint26: '',
      restraint36: '',
      restraint46: '',
      restraint56: '',
      restraint66: '',
      restraint76: '',
      restraint86: '',
      restraint96: '',
    },
    adverse_reaction: {
      restraint07: '',
      restraint17: '',
      restraint27: '',
      restraint37: '',
      restraint47: '',
      restraint57: '',
      restraint67: '',
      restraint77: '',
      restraint87: '',
      restraint97: '',
    },
    prevention: {
      restraint08: '',
      restraint18: '',
      restraint28: '',
      restraint38: '',
      restraint48: '',
      restraint58: '',
      restraint68: '',
      restraint78: '',
      restraint88: '',
      restraint98: '',
    },
  },
  ipc: {
    ipc00: '',
    ipc10: '',
    ipc20: '',
    ipc30: '',
    ipc40: '',
    ipc50: '',
    ipc60: '',
    ipc70: '',
    ipc80: '',
    ipc90: '',
  },
  vent: {
    date: {
      vent00: '',
      vent10: '',
      vent20: '',
      vent30: '',
      vent40: '',
      vent50: '',
      vent60: '',
      vent70: '',
      vent80: '',
      vent90: '',
    },
    mode: {
      vent01: '',
      vent11: '',
      vent21: '',
      vent31: '',
      vent41: '',
      vent51: '',
      vent61: '',
      vent71: '',
      vent81: '',
      vent91: '',
    },
    fio2: {
      vent02: '',
      vent12: '',
      vent22: '',
      vent32: '',
      vent42: '',
      vent52: '',
      vent62: '',
      vent72: '',
      vent82: '',
      vent92: '',
    },
    peep: {
      vent03: '',
      vent13: '',
      vent23: '',
      vent33: '',
      vent43: '',
      vent53: '',
      vent63: '',
      vent73: '',
      vent83: '',
      vent93: '',
    },
    f: {
      vent04: '',
      vent14: '',
      vent24: '',
      vent34: '',
      vent44: '',
      vent54: '',
      vent64: '',
      vent74: '',
      vent84: '',
      vent94: '',
    },
    vsennse: {
      vent05: '',
      vent15: '',
      vent25: '',
      vent35: '',
      vent45: '',
      vent55: '',
      vent65: '',
      vent75: '',
      vent85: '',
      vent95: '',
    },
    pi: {
      vent06: '',
      vent16: '',
      vent26: '',
      vent36: '',
      vent46: '',
      vent56: '',
      vent66: '',
      vent76: '',
      vent86: '',
      vent96: '',
    },
    ti: {
      vent07: '',
      vent17: '',
      vent27: '',
      vent37: '',
      vent47: '',
      vent57: '',
      vent67: '',
      vent77: '',
      vent87: '',
      vent97: '',
    },
    tv: {
      vent08: '',
      vent18: '',
      vent28: '',
      vent38: '',
      vent48: '',
      vent58: '',
      vent68: '',
      vent78: '',
      vent88: '',
      vent98: '',
    },
    mv: {
      vent09: '',
      vent19: '',
      vent29: '',
      vent39: '',
      vent49: '',
      vent59: '',
      vent69: '',
      vent79: '',
      vent89: '',
      vent99: '',
    },
    cstat: {
      vent010: '',
      vent110: '',
      vent210: '',
      vent310: '',
      vent410: '',
      vent510: '',
      vent610: '',
      vent710: '',
      vent810: '',
      vent910: '',
    },
    pf_ration: {
      vent011: '',
      vent111: '',
      vent211: '',
      vent311: '',
      vent411: '',
      vent511: '',
      vent611: '',
      vent711: '',
      vent811: '',
      vent911: '',
    },
  },
  crrt: {
    mode: {
      crrt00: '',
      crrt10: '',
      crrt20: '',
      crrt30: '',
      crrt40: '',
      crrt50: '',
      crrt60: '',
      crrt70: '',
      crrt80: '',
      crrt90: '',
    },
    blood_flow: {
      crrt01: '',
      crrt11: '',
      crrt21: '',
      crrt31: '',
      crrt41: '',
      crrt51: '',
      crrt61: '',
      crrt71: '',
      crrt81: '',
      crrt91: '',
    },
    dialysate: {
      crrt02: '',
      crrt12: '',
      crrt22: '',
      crrt32: '',
      crrt42: '',
      crrt52: '',
      crrt62: '',
      crrt72: '',
      crrt82: '',
      crrt92: '',
    },
    pre: {
      crrt03: '',
      crrt13: '',
      crrt23: '',
      crrt33: '',
      crrt43: '',
      crrt53: '',
      crrt63: '',
      crrt73: '',
      crrt83: '',
      crrt93: '',
    },
    post: {
      crrt04: '',
      crrt14: '',
      crrt24: '',
      crrt34: '',
      crrt44: '',
      crrt54: '',
      crrt64: '',
      crrt74: '',
      crrt84: '',
      crrt94: '',
    },
    pbp: {
      crrt05: '',
      crrt15: '',
      crrt25: '',
      crrt35: '',
      crrt45: '',
      crrt55: '',
      crrt65: '',
      crrt75: '',
      crrt85: '',
      crrt95: '',
    },
    pt_fluid_rmv: {
      crrt06: '',
      crrt16: '',
      crrt26: '',
      crrt36: '',
      crrt46: '',
      crrt56: '',
      crrt66: '',
      crrt76: '',
      crrt86: '',
      crrt96: '',
    },
    anti_coagulation: {
      crrt07: '',
      crrt17: '',
      crrt27: '',
      crrt37: '',
      crrt47: '',
      crrt57: '',
      crrt67: '',
      crrt77: '',
      crrt87: '',
      crrt97: '',
    },
    crrt_ck: {
      crrt08: '',
      crrt18: '',
      crrt28: '',
      crrt38: '',
      crrt48: '',
      crrt58: '',
      crrt68: '',
      crrt78: '',
      crrt88: '',
      crrt98: '',
    },
    access_prs: {
      crrt09: '',
      crrt19: '',
      crrt29: '',
      crrt39: '',
      crrt49: '',
      crrt59: '',
      crrt69: '',
      crrt79: '',
      crrt89: '',
      crrt99: '',
    },
    return_prs: {
      crrt010: '',
      crrt110: '',
      crrt210: '',
      crrt310: '',
      crrt410: '',
      crrt510: '',
      crrt610: '',
      crrt710: '',
      crrt810: '',
      crrt910: '',
    },
    filter_prs: {
      crrt011: '',
      crrt111: '',
      crrt211: '',
      crrt311: '',
      crrt411: '',
      crrt511: '',
      crrt611: '',
      crrt711: '',
      crrt811: '',
      crrt911: '',
    },
    effluent_prs: {
      crrt012: '',
      crrt112: '',
      crrt212: '',
      crrt312: '',
      crrt412: '',
      crrt512: '',
      crrt612: '',
      crrt712: '',
      crrt812: '',
      crrt912: '',
    },
    tmp_prs: {
      crrt013: '',
      crrt113: '',
      crrt213: '',
      crrt313: '',
      crrt413: '',
      crrt513: '',
      crrt613: '',
      crrt713: '',
      crrt813: '',
      crrt913: '',
    },
    prs_drop: {
      crrt014: '',
      crrt114: '',
      crrt214: '',
      crrt314: '',
      crrt414: '',
      crrt514: '',
      crrt614: '',
      crrt714: '',
      crrt814: '',
      crrt914: '',
    },
  },
};

export const initialGlucose = {
  update_at: '',
  blood_sugar_log: [],
  prescription: [],
};

export const initialBedScore = {
  date: '',
  update_at: '',
  contents: {
    sensoryPerception: '',
    humidity: '',
    activity: '',
    mobility: '',
    nutrition: '',
    frictionAndDissolutionForce: '',
  },
};

export const initialBedScoreTwo = {
  date: '',
  update_at: '',
  contents: {
    sensoryPerception: '',
    humidity: '',
    activity: '',
    mobility: '',
    nutrition: '',
    frictionAndDissolutionForce: '',
  },
};

export const initialNeeds = {
  date: '',
  update_at: '',
  body_status: {
    takeOffClothes: '',
    eat: '',
    sitUp: '',
    toilet: '',
    washFace: '',
    bath: '',
    transfer: '',
    controlStool: '',
    brushTeeth: '',
    changePosition: '',
    getOutRoom: '',
    controlUrine: '',
  },
  disease_status: {
    chronic: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked4: false,
      cancer: '',
    },
    circulatory: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked4: false,
      checked5: false,
      etc: '',
    },
    nervous: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked5: false,
      etc: '',
    },
    musculoskeletal: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked5: false,
      etc: '',
    },
    mentalAndBehavioral: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked5: false,
      etc: '',
    },
    respiratory: {
      checked1: false,
      checked2: false,
      checked5: false,
      etc: '',
    },
    renal: {
      checked1: false,
      checked5: false,
      etc: '',
    },
    other: {
      checked1: false,
      checked5: false,
      allergy: '',
      etc: '',
    },
  },
  reason1: '',
  reason2: '',
};

export const initialFall = {
  date: '',
  update_at: '',
  contents: {
    experience: '',
    diagnosis: '',
    walkingAids: '',
    intravenousLine: '',
    gait: '',
    consciousness: '',
  },
};

export const initialFallTwo = {
  date: '',
  update_at: '',
  contents: {
    experience: '',
    diagnosis: '',
    walkingAids: '',
    intravenousLine: '',
    gait: '',
    consciousness: '',
  },
};

export const initialPediatric_fall = {
  date: '',
  update_at: '',
  contents: {
    age: '',
    diagnosis: '',
    sex: '',
    cognitive_disorder: '',
    environmental_factors: '',
    medication_use: '',
    surgical_sedative_anesthetic_factors: '',
  },
};

export const initialGCS = {
  date: '',
  update_at: '',
  eye_opening: '',
  verbal_response: '',
  motor_response: '',
};

export const initialPediatric_GCS = {
  date: '',
  update_at: '',
  eye_opening: '',
  verbal_response: '',
  motor_response: '',
};

export const initialFourScore = {
  date: '',
  update_at: '',
  eye_opening: '',
  brainstem_reflexes: '',
  motor_response: '',
  respiration: '',
};

export const initialSafety = {
  update_at: '',
  accident_consequences_details: {
    accidence_date: '',
    discovery_date: '',
    discovery_place: '',
    discovery_place_etc: '',
    accident_type: '',
    accident_classification: '',
    accident_classification_etc: '',
  },
  event_classification: '',
  falling_type: {
    consciousness_level: '',
    activity_status: '',
    assisting_devices: '',
    place_falling_accident: '',
    place_falling_accident_etc: '',
    patient_risk_factors: '',
    score: 0,
    date: '',
    fall_type: '',
    risk_factor: '',
    risk_factor_etc: '',
  },
  medication_type: {
    prescription_error: '',
    prescription_error_etc: '',
    drug_preparation_error: '',
    drug_preparation_error_etc: '',
    confirm_error: '',
    interpretation_error: '',
  },
  other_type: '',
  other_type_etc: '',
  accident_detail: '',
  accident_handling: '',
  accident_result: '',
};

export const initialNRS = {
  update_at: '',
  catholic_nrs_survey: [],
};

export const initialFLACC = {
  update_at: '',
  flacc_survey: [],
};

export const initialCNPS = {
  update_at: '',
  face: '',
  activity: '',
  respiratory: '',
  vocalization: '',
  sum: '',
};

export const initialMentalNursing = {
  update_at: '',
  mental_survey: [],
};

export const initialIoCheckRecord = {
  update_at: '',
  io_survey: [],
};

export const initialBDI = {
  update_at: '',
  content: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  sum: 0,
};

export const initialBAI = {
  update_at: '',
  content: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  sum: 0,
};

export const initialMMSE = {
  update_at: '',
  score: [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  sum: 0,
};

export const initialCIST = {
  update_at: '',
  orientation1: '',
  orientation2: '',
  orientation3: '',
  orientation4: '',
  orientation5: '',
  memory1: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
  },
  memory2: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
  },
  attention1: '',
  attention2: '',
  attention3: '',
  visual_spatial_ability: '',
  executive_function1_1: '',
  executive_function1_2: '',
  executive_function1_3: '',
  memory3: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
  },
  memory4: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
    checked6: false,
    checked7: false,
    checked8: false,
    checked9: false,
    checked10: false,
    checked11: false,
    checked12: false,
    checked13: false,
    checked14: false,
    checked15: false,
  },
  language_function1: '',
  language_function2: '',
  language_function3: '',
  language_function4: '',
  executive_function2: '',
};

export const initialOperation = {
  update_at: '',
  surgery_information: {
    operating_surgeon: '',
    assistant: '',
    scrubbing_nurse: '',
    circulating_nurse: '',
  },
  operation_information: {
    operating_department: '',
    operating_date: '',
    operating_time: '',
    asa_class: '',
    main_operation_name: '',
    minor_operation_name: '',
    past_history: '',
    allergy: '',
    npo_status: '',
    prophylactic_antibiotics: '',
    position: '',
    position_etc: '',
    preoperative_xray: true,
    preoperative_ekg: true,
  },
  surgery_details: {
    content: '',
    arrival_time: '',
    anesthesia_start_time: '',
    surgery_start_time: '',
    surgery_end_time: '',
    anesthesia_end_time: '',
    discharge_time: '',
    anesthetic_method: '',
    anesthetic_method_etc: '',
    anesthesiologist: '',
  },
};

export const initialAnesthesia = {
  update_at: '',
  operation_information: {
    operating_department: '',
    operating_allergy: '',
    operating_date: '',
    operating_time: '',
    operation_name: '',
    npo_status: '',
    position: '',
    position_etc: '',
    past_history_and_allergy: '',
    preoperative_xray: false,
    preoperative_ekg: false,
    emergency_status: '',
    asa_class: '',
    prophylactic_antibiotics: '',
    prophylactic_method: '',
    prophylactic_method_etc: '',
  },
  prescription_record: [],
  patient_status_record: {
    infusion_amount: '',
    transfusion_amount: '',
    intake_etc: '',
    urine_amount: '',
    blood_clot_amount: '',
    output_etc: '',
  },
  patient_status_list_record: [],
};

export const initialTransfusion = {
  update_at: '',
  blood_number: '',

  blood_product: '',

  blood_name: '',
  volume: '',

  pre_dose: '',
  irradiation: '',
  filtering: '',
  education: '',
  confirm_transfusion: '',

  arrival_time: '',
  blood_transfusion_arrival: '',
  transfusion_check1: '',
  transfusion_check2: '',
  transfusion_start_time: '',
  practitioner_start: '',
  transfusion_end_time: '',
  practitioner_end: '',
  transfusion_record: [],
  nursing_implementation: '',
};

export const initialCPR = {
  update_at: '',
  find_date: '',
  find_time: '',
  terminate_reason: '',
  clinical_observation: {
    bp0: '',
    hr0: '',
    rr0: '',
    bt0: '',
    spo20: '',
    consciousness0: '',
    pupil_size0: '',
    pupil_reflex0: '',
    cardio_ryt0: '',
    bp1: '',
    hr1: '',
    rr1: '',
    bt1: '',
    spo21: '',
    consciousness1: '',
    pupil_size1: '',
    pupil_reflex1: '',
    cardio_ryt1: '',
    bp2: '',
    hr2: '',
    rr2: '',
    bt2: '',
    spo22: '',
    consciousness2: '',
    pupil_size2: '',
    pupil_reflex2: '',
    cardio_ryt2: '',
    bp3: '',
    hr3: '',
    rr3: '',
    bt3: '',
    spo23: '',
    consciousness3: '',
    pupil_size3: '',
    pupil_reflex3: '',
    cardio_ryt3: '',
    bp4: '',
    hr4: '',
    rr4: '',
    bt4: '',
    spo24: '',
    consciousness4: '',
    pupil_size4: '',
    pupil_reflex4: '',
    cardio_ryt4: '',
    bp5: '',
    hr5: '',
    rr5: '',
    bt5: '',
    spo25: '',
    consciousness5: '',
    pupil_size5: '',
    pupil_reflex5: '',
    cardio_ryt5: '',
    bp6: '',
    hr6: '',
    rr6: '',
    bt6: '',
    spo26: '',
    consciousness6: '',
    pupil_size6: '',
    pupil_reflex6: '',
    cardio_ryt6: '',
    bp7: '',
    hr7: '',
    rr7: '',
    bt7: '',
    spo27: '',
    consciousness7: '',
    pupil_size7: '',
    pupil_reflex7: '',
    cardio_ryt7: '',
    bp8: '',
    hr8: '',
    rr8: '',
    bt8: '',
    spo28: '',
    consciousness8: '',
    pupil_size8: '',
    pupil_reflex8: '',
    cardio_ryt8: '',
    bp9: '',
    hr9: '',
    rr9: '',
    bt9: '',
    sp929: '',
    consciousness9: '',
    pupil_size9: '',
    pupil_reflex9: '',
    cardio_ryt9: '',
    bp10: '',
    hr10: '',
    rr10: '',
    bt10: '',
    spo210: '',
    consciousness10: '',
    pupil_size10: '',
    pupil_reflex10: '',
    cardio_ryt10: '',
    bp11: '',
    hr11: '',
    rr11: '',
    bt11: '',
    spo211: '',
    consciousness11: '',
    pupil_size11: '',
    pupil_reflex11: '',
    cardio_ryt11: '',
    bp12: '',
    hr12: '',
    rr12: '',
    bt12: '',
    spo212: '',
    consciousness12: '',
    pupil_size12: '',
    pupil_reflex12: '',
    cardio_ryt12: '',
    bp13: '',
    hr13: '',
    rr13: '',
    bt13: '',
    spo213: '',
    consciousness13: '',
    pupil_size13: '',
    pupil_reflex13: '',
    cardio_ryt13: '',
    bp14: '',
    hr14: '',
    rr14: '',
    bt14: '',
    spo214: '',
    consciousness14: '',
    pupil_size14: '',
    pupil_reflex14: '',
    cardio_ryt14: '',
    bp15: '',
    hr15: '',
    rr15: '',
    bt15: '',
    spo215: '',
    consciousness15: '',
    pupil_size15: '',
    pupil_reflex15: '',
    cardio_ryt15: '',
    bp16: '',
    hr16: '',
    rr16: '',
    bt16: '',
    spo216: '',
    consciousness16: '',
    pupil_size16: '',
    pupil_reflex16: '',
    cardio_ryt16: '',
    bp17: '',
    hr17: '',
    rr17: '',
    bt17: '',
    spo217: '',
    consciousness17: '',
    pupil_size17: '',
    pupil_reflex17: '',
    cardio_ryt17: '',
    bp18: '',
    hr18: '',
    rr18: '',
    bt18: '',
    spo218: '',
    consciousness18: '',
    pupil_size18: '',
    pupil_reflex18: '',
    cardio_ryt18: '',
    bp19: '',
    hr19: '',
    rr19: '',
    bt19: '',
    sp9219: '',
    consciousness19: '',
    pupil_size19: '',
    pupil_reflex19: '',
    cardio_ryt19: '',
    bp20: '',
    hr20: '',
    rr20: '',
    bt20: '',
    spo220: '',
    consciousness20: '',
    pupil_size20: '',
    pupil_reflex20: '',
    cardio_ryt20: '',
    bp21: '',
    hr21: '',
    rr21: '',
    bt21: '',
    spo221: '',
    consciousness21: '',
    pupil_size21: '',
    pupil_reflex21: '',
    cardio_ryt21: '',
  },
  treatment: {
    chest_compression0: '',
    artificial_ventilation0: true,
    aed0: '',
    chest_compression1: '',
    artificial_ventilation1: true,
    aed1: '',
    chest_compression2: '',
    artificial_ventilation2: true,
    aed2: '',
    chest_compression3: '',
    artificial_ventilation3: true,
    aed3: '',
    chest_compression4: '',
    artificial_ventilation4: true,
    aed4: '',
    chest_compression5: '',
    artificial_ventilation5: true,
    aed5: '',
    chest_compression6: '',
    artificial_ventilation6: true,
    aed6: '',
    chest_compression7: '',
    artificial_ventilation7: true,
    aed7: '',
    chest_compression8: '',
    artificial_ventilation8: true,
    aed8: '',
    chest_compression9: '',
    artificial_ventilation9: true,
    aed9: '',
    chest_compression10: '',
    artificial_ventilation10: true,
    aed10: '',
    chest_compression11: '',
    artificial_ventilation11: true,
    aed11: '',
    chest_compression12: '',
    artificial_ventilation12: true,
    aed12: '',
    chest_compression13: '',
    artificial_ventilation13: true,
    aed13: '',
    chest_compression14: '',
    artificial_ventilation14: true,
    aed14: '',
    chest_compression15: '',
    artificial_ventilation15: true,
    aed15: '',
    chest_compression16: '',
    artificial_ventilation16: true,
    aed16: '',
    chest_compression17: '',
    artificial_ventilation17: true,
    aed17: '',
    chest_compression18: '',
    artificial_ventilation18: true,
    aed18: '',
    chest_compression19: '',
    artificial_ventilation19: true,
    aed19: '',
    chest_compression20: '',
    artificial_ventilation20: true,
    aed20: '',
    chest_compression21: '',
    artificial_ventilation21: true,
    aed21: '',
  },
  intubation: {
    id0: '',
    depth0: '',
    balloon0: '',
    times0: '',
    practitioner0: '',
    id1: '',
    depth1: '',
    balloon1: '',
    times1: '',
    practitioner1: '',
    id2: '',
    depth2: '',
    balloon2: '',
    times2: '',
    practitioner2: '',
    id3: '',
    depth3: '',
    balloon3: '',
    times3: '',
    practitioner3: '',
    id4: '',
    depth4: '',
    balloon4: '',
    times4: '',
    practitioner4: '',
    id5: '',
    depth5: '',
    balloon5: '',
    times5: '',
    practitioner5: '',
    id6: '',
    depth6: '',
    balloon6: '',
    times6: '',
    practitioner6: '',
    id7: '',
    depth7: '',
    balloon7: '',
    times7: '',
    practitioner7: '',
    id8: '',
    depth8: '',
    balloon8: '',
    times8: '',
    practitioner8: '',
    id9: '',
    depth9: '',
    balloon9: '',
    times9: '',
    practitioner9: '',
    id10: '',
    depth10: '',
    balloon10: '',
    times10: '',
    practitioner10: '',
    id11: '',
    depth11: '',
    balloon11: '',
    times11: '',
    practitioner11: '',
    id12: '',
    depth12: '',
    balloon12: '',
    times12: '',
    practitioner12: '',
    id13: '',
    depth13: '',
    balloon13: '',
    times13: '',
    practitioner13: '',
    id14: '',
    depth14: '',
    balloon14: '',
    times14: '',
    practitioner14: '',
    id15: '',
    depth15: '',
    balloon15: '',
    times15: '',
    practitioner15: '',
    id16: '',
    depth16: '',
    balloon16: '',
    times16: '',
    practitioner16: '',
    id17: '',
    depth17: '',
    balloon17: '',
    times17: '',
    practitioner17: '',
    id18: '',
    depth18: '',
    balloon18: '',
    times18: '',
    practitioner18: '',
    id19: '',
    depth19: '',
    balloon19: '',
    times19: '',
    practitioner19: '',
    id20: '',
    depth20: '',
    balloon20: '',
    times20: '',
    practitioner20: '',
    id21: '',
    depth21: '',
    balloon21: '',
    times21: '',
    practitioner21: '',
  },
  medication: {
    no00_1: '',
    no00_2: '',
    no00_3: '',
    no00_4: '',
    no00_5: '',
    no00_6: '',
    no00_7: '',
    no0_1: '',
    no0_2: '',
    no0_3: '',
    no0_4: '',
    no0_5: '',
    no0_6: '',
    no0_7: '',
    no1_1: '',
    no1_2: '',
    no1_3: '',
    no1_4: '',
    no1_5: '',
    no1_6: '',
    no1_7: '',
    no2_1: '',
    no2_2: '',
    no2_3: '',
    no2_4: '',
    no2_5: '',
    no2_6: '',
    no2_7: '',
    no3_1: '',
    no3_2: '',
    no3_3: '',
    no3_4: '',
    no3_5: '',
    no3_6: '',
    no3_7: '',
    no4_1: '',
    no4_2: '',
    no4_3: '',
    no4_4: '',
    no4_5: '',
    no4_6: '',
    no4_7: '',
    no5_1: '',
    no5_2: '',
    no5_3: '',
    no5_4: '',
    no5_5: '',
    no5_6: '',
    no5_7: '',
    no6_1: '',
    no6_2: '',
    no6_3: '',
    no6_4: '',
    no6_5: '',
    no6_6: '',
    no6_7: '',
    no7_1: '',
    no7_2: '',
    no7_3: '',
    no7_4: '',
    no7_5: '',
    no7_6: '',
    no7_7: '',
    no8_1: '',
    no8_2: '',
    no8_3: '',
    no8_4: '',
    no8_5: '',
    no8_6: '',
    no8_7: '',
    no9_1: '',
    no9_2: '',
    no9_3: '',
    no9_4: '',
    no9_5: '',
    no9_6: '',
    no9_7: '',
    no10_1: '',
    no10_2: '',
    no10_3: '',
    no10_4: '',
    no10_5: '',
    no10_6: '',
    no10_7: '',
    no10__1: '',
    no10__2: '',
    no10__3: '',
    no10__4: '',
    no10__5: '',
    no10__6: '',
    no10__7: '',
    no11_1: '',
    no11_2: '',
    no11_3: '',
    no11_4: '',
    no11_5: '',
    no11_6: '',
    no11_7: '',
    no12_1: '',
    no12_2: '',
    no12_3: '',
    no12_4: '',
    no12_5: '',
    no12_6: '',
    no12_7: '',
    no13_1: '',
    no13_2: '',
    no13_3: '',
    no13_4: '',
    no13_5: '',
    no13_6: '',
    no13_7: '',
    no14_1: '',
    no14_2: '',
    no14_3: '',
    no14_4: '',
    no14_5: '',
    no14_6: '',
    no14_7: '',
    no15_1: '',
    no15_2: '',
    no15_3: '',
    no15_4: '',
    no15_5: '',
    no15_6: '',
    no15_7: '',
    no16_1: '',
    no16_2: '',
    no16_3: '',
    no16_4: '',
    no16_5: '',
    no16_6: '',
    no16_7: '',
    no17_1: '',
    no17_2: '',
    no17_3: '',
    no17_4: '',
    no17_5: '',
    no17_6: '',
    no17_7: '',
    no18_1: '',
    no18_2: '',
    no18_3: '',
    no18_4: '',
    no18_5: '',
    no18_6: '',
    no18_7: '',
    no19_1: '',
    no19_2: '',
    no19_3: '',
    no19_4: '',
    no19_5: '',
    no19_6: '',
    no19_7: '',
    no20_1: '',
    no20_2: '',
    no20_3: '',
    no20_4: '',
    no20_5: '',
    no20_6: '',
    no20_7: '',
    no21_1: '',
    no21_2: '',
    no21_3: '',
    no21_4: '',
    no21_5: '',
    no21_6: '',
    no21_7: '',
  },
  test: {
    abga0: false,
    chest0: false,
    abga1: false,
    chest1: false,
    abga2: false,
    chest2: false,
    abga3: false,
    chest3: false,
    abga4: false,
    chest4: false,
    abga5: false,
    chest5: false,
    abga6: false,
    chest6: false,
    abga7: false,
    chest7: false,
    abga8: false,
    chest8: false,
    abga9: false,
    chest9: false,
    abga10: false,
    chest10: false,
    abga11: false,
    chest11: false,
    abga12: false,
    chest12: false,
    abga13: false,
    chest13: false,
    abga14: false,
    chest14: false,
    abga15: false,
    chest15: false,
    abga16: false,
    chest16: false,
    abga17: false,
    chest17: false,
    abga18: false,
    chest18: false,
    abga19: false,
    chest19: false,
    abga20: false,
    chest20: false,
    abga21: false,
    chest21: false,
  },
};

export const initialDialysis = {
  update_at: '',
  date: '',
  time: '',
  visiting_route: '',
  visiting_route_etc: '',
  dialysis_machine: '',
  dialyzer: '',
  dialysate: '',
  vascular_access: '',
  vascular_access_etc: '',
  starting_nurse: '',
  ending_nurse: '',
  pre_previous_weight: '',
  pre_today_weight: '',
  pre_weight_change: '',
  post_previous_weight: '',
  post_today_weight: '',
  post_weight_change: '',
  dialysis_db: [],
  crrt: [],
  additional_information: '',
};

export const initialIntubation = {
  update_at: '',
  picc_and_more1: [],
  picc_and_more2: [],
  picc_and_more3: [],
  picc_and_more4: [],
  picc_and_more5: [],
  pca: [],
  ltube: [],
  jpbag: [],
  foley: [],
  etube: [],
};

export const initialEmergency = {
  update_at: '',
  emergency_information: {
    accident_date: '',
    accident_time: '',
    visit_method: '',
    memo: '',
    arrival_time: '',
  },
  emergency_patient_information: {
    symptom: '',
    etc_symptom: '',
    damage: '',
    intentional: '',
    medical_conditions: '',
    history: '',
    allergy: '',
    medication: '',
    consciousness: '',
    gcs: '',
    motor: '',
    pupil: '',
    nrs: '',
    pqrst: '',
    ktas: '',
    expected_diagnosis: '',
  },
  patient_status_record: {
    infusion_amount: '',
    transfusion_amount: '',
    intake_etc: '',
    urine_amount: '',
    blood_clot_amount: '',
    output_etc: '',
  },
  patient_status_list_record: [],
  emergency_care_result: {
    result: { value: 1, input: '' },
    status: {
      checked1: false,
      checked2: false,
      checked3: false,
      checked4: false,
      placeholder: '',
    },
  },
};

export const initialChildbirth = {
  update_at: '',
  child_birth_information: {
    date: '',
    time: '',
    type: '',
  },
  newborn_condition: {
    gender: -1,
    weight: '',
    apgar_score1m: '',
    apgar_score5m: '',
    oxygen_intake: -1,
    first_urine: -1,
    placenta_discharge: -1,
    fetal_staining: -1,
    nuchal_cord: -1,
    nuchal_cord_content: '',
    resuscitation: -1,
    resuscitation_content: '',
    specifications: '',
  },
  apgar: {
    appearance: -1,
    pulse: -1,
    grimace: -1,
    activity: -1,
    respiration: -1,
  },
  placenta_removal: {
    time: '',
    methods: -1,
    curettage: -1,
  },
  maternal_condition: {
    episiotomy: -1,
    episiotomy_content: '',
    perineal_laceration: -1,
    perineal_laceration_content: '',
    uterus_contraction: '',
  },
  nursing_records: [],
};

export const initialHomeCare = {
  update_at: '',
  basic_information: {
    occupation: '',
    insurance_type: '',
    residence: '',
    residence_etc: '',
    religion: '',
    nursing_provider: '',
    sanitary: '',
    sanitary_notes: '',
    marital_status: '',
    past_history: '',
    safety: '',
    safety_notes: '',
  },
  request_status: [],
  inspection_findings: [],
  medication_records: [],
  need_service: '',
};

export const initialKPCS = {
  date: '',
  update_at: '',
  no01: 0,
  no02: 0,
  no03: 0,
  no04: 0,
  no05: 0,
  no06: 0,
  no07: 0,
  no08: 0,
  no09: 0,
  no10: 0,
  no11: 0,
  no12: 0,
  no13: 0,
  no14: 0,
  no15: 0,
  no16: 0,
  no17: 0,
  no18: 0,
  no19: 0,
  no20: 0,
  no21: 0,
  no22: 0,
  no22_1: 0,
  no23: 0,
  no23_1: 0,
  no24: 0,
  no25: 0,
  no26: 0,
  no27: 0,
  no28: 0,
  no29: 0,
  no30: 0,
  no31: 0,
  no32: 0,
  no32_1: 0,
  no33: 0,
  no34: 0,
  no35: 0,
  no36: 0,
  no37: 0,
  no38: 0,
  no39: 0,
  no40: 0,
  no41: 0,
  no42: 0,
  no43: 0,
  no44: 0,
  no45: 0,
  no46: 0,
  no47: 0,
  no47_1: 0,
  no48: 0,
  no49: 0,
  no50: 0,
};

export const initialKPCS_ICU = {
  date: '',
  update_at: '',
  no01: 0,
  no02: 0,
  no03: 0,
  no04: 0,
  no05: 0,
  no06: 0,
  no07: 0,
  no08: 0,
  no09: 0,
  no10: 0,
  no11: 0,
  no12: 0,
  no13: 0,
  no14: 0,
  no15: 0,
  no16: 0,
  no17: 0,
  no18: 0,
  no19: 0,
  no20: 0,
  no21: 0,
  no22: 0,
  no23: 0,
  no24: 0,
  no25: 0,
  no26: 0,
  no27: 0,
  no28: 0,
  no29: 0,
  no30: 0,
  no30_1: 0,
  no31: 0,
  no32: 0,
  no33: 0,
  no33_1: 0,
  no34: 0,
  no34_1: 0,
  no35: 0,
  no36: 0,
  no37: 0,
  no38: 0,
  no39: 0,
  no40: 0,
  no40_1: 0,
  no41: 0,
  no41_1: 0,
  no42: 0,
  no43: 0,
  no43_1: 0,
  no44: 0,
  no45: 0,
  no45_1: 0,
  no46: 0,
  no47: 0,
  no47_1: 0,
  no48: 0,
  no48_1: 0,
  no49: 0,
  no49_1: 0,
  no50: 0,
  no50_1: 0,
  no51: 0,
  no51_1: 0,
  no52: 0,
  no53: 0,
  no54: 0,
  no55: 0,
  no56: 0,
  no57: 0,
  no58: 0,
  no58_1: 0,
  no59: 0,
  no60: 0,
  no61: 0,
  no61_1: 0,
  no62: 0,
  no62_1: 0,
  no63: 0,
  no64: 0,
  no65: 0,
  no66: 0,
  no67: 0,
  no68: 0,
  no69: 0,
  no70: 0,
  no71: 0,
  no72: 0,
  no73: 0,
  no74: 0,
  no75: 0,
  no76: 0,
  no77: 0,
  no77_1: 0,
  no78: 0,
  no79: 0,
  no80: 0,
  no81: 0,
  no82: 0,
};

export const initialDietList = {
  update_at: '',
  birth: '',
  classification: 1,

  //  조식
  break_fast: {
    guardian_meal: false,
    basic_meal: 0,
    therapeutic_intestinal: '',
    therapeutic_kidney: '',
    therapeutic_liver: '',
    controlled_diet: '',
    specifics1: '',
    specifics2: '',
    specifics3: '',
    specifics4: '',
    specifics_etc: '',
  },
  lunch: {
    guardian_meal: false,
    basic_meal: 0,
    therapeutic_intestinal: '',
    therapeutic_kidney: '',
    therapeutic_liver: '',
    controlled_diet: '',
    specifics1: '',
    specifics2: '',
    specifics3: '',
    specifics4: '',
    specifics_etc: '',
  },
  dinner: {
    guardian_meal: false,
    basic_meal: 0,
    therapeutic_intestinal: '',
    therapeutic_kidney: '',
    therapeutic_liver: '',
    controlled_diet: '',
    specifics1: '',
    specifics2: '',
    specifics3: '',
    specifics4: '',
    specifics_etc: '',
  },
};

export const initialHospitalConfirm = {
  update_at: '',
  nursing_care: {
    checked1: false,
  },
  facilities_in: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
    checked6: false,
    checked7: false,
    checked8: false,
  },
  facilities: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
    checked6: false,
    checked7: false,
    checked8: false,
    checked9: false,
    checked10: false,
    checked11: false,
    checked12: false,
    checked13: false,
    checked14: false,
    checked15: false,
    checked16: false,
  },
  name: '',
  relationship: '',
  signature: '',
  date: '',
  personnel_signature: '',
};

export const initialFallConfirm = {
  update_at: '',
  fall_education: {
    checked1: false,
    checked2: false,
    checked3: false,
    checked4: false,
    checked5: false,
    checked6: false,
    checked7: false,
    checked8: false,
  },
  signature: '',
  date: '',
  personnel_signature: '',
};

export const initialTransfusionAgree = {
  update_at: '',
  pt_bday: '',
  pt_contact: '',
  pt_name: '',
  pt_sig: '',

  representative_bday: '',
  representative_contact: '',
  representative_name: '',
  representative_sig: '',

  dr_name: '',
  dr_sig: '',
};

export const initialCRRT = {
  update_at: '',
  no1_1: '',
  no1_2: '',
  no2: '',
  no3_1: '',

  date: '',
  relationship: '',
  name: '',
  applier_contact: '',
  sign: '',
};

export const initialCentralVenous = {
  update_at: '',
  pt_name: '',
  pt_ssn: '',
  pt_addr: '',
  pt_contact: '',

  applier_name: '',
  applier_relp: '',
  applier_bday: '',
  applier_contact: '',
  applier_addr: '',

  scope_center: '',
  scope_period_from: '',
  scope_period_to: '',
  scope_reason: '',
  scope_detail: '',

  date: '',
  name: '',
  sig: '',
};

export const initialColonoscopy = {
  update_at: '',
  agree_check_01: '',
  agree_check_02: '',
  patient_bday: '',
  patient_contact: '',
  patient_name: '',
  patient_sig: '',
  companion_bday: '',
  companion_contact: '',
  companion_name: '',
  companion_sig: '',
  dr_name: '',
  dr_sig: '',
};

export const initialUpperEndoscopy = {
  update_at: '',
  agree_check: '',
  patient_bday: '',
  patient_contact: '',
  patient_name: '',
  patient_sig: '',
  companion_bday: '',
  companion_contact: '',
  companion_name: '',
  companion_sig: '',
  dr_name: '',
  dr_sig: '',
};

export const initialNonSalary = {
  update_at: '',
  item_01: '',
  fee_01: '',
  no_01: true,

  item_02: '',
  fee_02: '',
  no_02: true,

  item_03: '',
  fee_03: '',
  no_03: true,

  item_04: '',
  fee_04: '',
  no_04: true,

  date: '',
  name: '',
  sig: '',
};

export const initialMedicalRecords = {
  update_at: '',
  pt_name: '',
  pt_ssn: '',
  pt_addr: '',
  pt_contact: '',

  applier_name: '',
  applier_relp: '',
  applier_bday: '',
  applier_contact: '',
  applier_addr: '',

  scope_center: '',
  scope_period_from: '',
  scope_period_to: '',
  scope_reason: '',
  scope_detail: '',

  date: '',
  name: '',
  sig: '',
};

export const initialSuppressor = {
  update_at: '',
  no2_1: '',
  no2_2: '',
  no2_3: '',
  no2_4: '',
  no2_5: '',
  no2_dr_name: '',
  no2_dr_sign: '',

  no3_check_01: false,
  no3_check_02: false,
  no3_check_03: false,
  no3_check_04: false,

  no3_input_box: '',
  date: '',
  relationship: '',
  name: '',
  sign: '',
  dr_name: '',
  dr_sign: '',
  ns_name: '',
  ns_sign: '',
};

export const initialDNR = {
  update_at: '',
  pt_name: '',
  pt_ssn: '',
  pt_addr: '',
  pt_contact: '',

  willing: '', //호스피스 이용 의향

  explanation01: false,
  explanation02: false,
  explanation03: false,
  explanation04: false,
  explanation05: false,
  explanation06: false,

  explanation_check: '',
  explanation_check_sig_date: '',
  explanation_check_sig_name: '',
  explanation_check_sig_sig: '',

  pt_available: '',
  pt_available_etc_memo: '',

  center_name: '',
  center_location: '',
  center_consultant: '',
  center_contact: '',

  recorde_date: '',
  recorde_person_name: '',
  recorde_person_sig: '',

  register_date: '',
  register_person_name: '',
  register_person_sig: '',
};

export const initialDNA = {
  update_at: '',
  test_object_name: '',
  test_object_ssn: '',
  test_object_addr: '',
  test_object_contact: '',

  legal_representative_name: '',
  legal_representative_ssn: '',
  legal_representative_addr: '',
  legal_representative_contact: '',

  lab_name: '',
  lab_contact: '',

  pt_purpose: '',
  pt_test: '',

  date: '',
  testee_name: '',
  testee_sig: '',
  representative_name: '',
  representative_sig: '',
  consultant_name: '',
  consultant_sig: '',
};

export const initialCoreNursingSkillVideo = {
  update_at: '',
  files: [],
};

export const initialCoreNursingSkillVideoExemple = {
  update_at: '',
  files: [],
};

export const initialCheckListRoom = {
  update_at: '',
  info_info01: '',
  info_info02: '',
  info_info03: '',

  info_mental01: '',

  fall01: '',
  fall02: '',
  fall03: '',
  fall04: '',
  fall05: '',

  bed_sore01: '',
  bed_sore02: '',
  bed_sore03: '',
  bed_sore04: '',
  bed_sore05: '',

  edu01: '',
  edu02: '',

  care_plan01: '',
  care_plan02: '',
  care_plan03: '',

  surgery01: '',
  surgery02: '',
  surgery03: '',

  medicine01: '',
  medicine02: '',

  hospitalization01: '',
  hospitalization02: '',
  hospitalization03: '',
  hospitalization04: '',
  hospitalization05: '',
  hospitalization06: '',
  hospitalization07: '',
  hospitalization08: '',

  ns_fall01: '',
  ns_fall02: '',

  ns_bedsore01: '',

  ns_pt_moving01: '',
  ns_pt_moving02: '',

  ns_edu01: '',

  ns_surgery01: '',

  ns_transfusion01: '',

  ns_infection01: '',

  ns_pain01: '',
  ns_pain02: '',
  ns_pain03: '',

  ns_re_pain01: '',
  ns_re_pain02: '',
  ns_re_pain03: '',
  ns_re_pain04: '',

  ns_pca01: '',
  ns_pca02: '',
  ns_pca03: '',
  ns_pca04: '',

  ns_nausea01: '',
  ns_nausea02: '',

  ns_chemo_side_eff01: '',

  ns_restraint01: '',
  ns_restraint02: '',
  ns_restraint03: '',
  ns_restraint04: '',
  ns_restraint05: '',

  ns_high_risk01: '',
  ns_high_risk02: '',

  right01: '',

  discharge01: '',
  discharge02: '',
  discharge03: '',
  discharge04: '',

  ocs01: '',
};

export const initialFFI = {
  update_at: '',
  ffi01: 0,
  ffi02: 0,
  ffi03: 0,
  ffi04: 0,
  ffi05: 0,
  ffi06: 0,
  ffi07: 0,
  ffi08: 0,

  ffi09: 0,
  ffi10: 0,
  ffi11: 0,
  ffi12: 0,
  ffi13: 0,
  ffi14: 0,
  ffi15: 0,
  ffi16: 0,
  ffi17: 0,
  ffi18: 0,

  ffi19: 0,
  ffi20: 0,
  ffi21: 0,
  ffi22: 0,
  ffi23: 0,
};

export const initialKOOS = {
  update_at: '',
  spt01: '',
  spt02: '',
  spt03: '',
  spt04: '',
  spt05: '',

  stf01: '',
  stf02: '',

  pain01: '',
  pain02: '',
  pain03: '',
  pain04: '',
  pain05: '',
  pain06: '',
  pain07: '',
  pain08: '',
  pain09: '',

  daily01: '',
  daily02: '',
  daily03: '',
  daily04: '',
  daily05: '',
  daily06: '',
  daily07: '',
  daily08: '',
  daily09: '',
  daily10: '',
  daily11: '',
  daily12: '',
  daily13: '',
  daily14: '',
  daily15: '',
  daily16: '',
  daily17: '',

  actv01: '',
  actv02: '',
  actv03: '',
  actv04: '',
  actv05: '',

  qol01: '',
  qol02: '',
  qol03: '',
  qol04: '',
};

export const initialLEFS = {
  update_at: '',
  lefs01: '',
  lefs02: '',
  lefs03: '',
  lefs04: '',
  lefs05: '',
  lefs06: '',
  lefs07: '',
  lefs08: '',
  lefs09: '',
  lefs10: '',
  lefs11: '',
  lefs12: '',
  lefs13: '',
  lefs14: '',
  lefs15: '',
  lefs16: '',
  lefs17: '',
  lefs18: '',
  lefs19: '',
  lefs20: '',
};

export const initialNDI = {
  update_at: '',
  ndi01: '',
  ndi02: '',
  ndi03: '',
  ndi04: '',
  ndi05: '',
  ndi06: '',
  ndi07: '',
  ndi08: '',
  ndi09: '',
  ndi10: '',
};

export const initialSTarTBack = {
  update_at: '',
  sb01: '',
  sb02: '',
  sb03: '',
  sb04: '',
  sb05: '',
  sb06: '',
  sb07: '',
  sb08: '',
  sb09: '',
};

export const initialNursingProcess = {
  update_at: '',
  nursing_process_narrative_note_survey: [],
};
