export const initialNursingRecord = {
  nanda: {
    domain: '',
    class: '',
    diagnosis: '',
    collectingData: '',
    goal: '',
    plan: '',
    interventions: '',
    evaluation: '',
  },
  soapie: {
    subjective: '',
    objective: '',
    assessment: '',
    planning: '',
    interventions: '',
    evaluation: '',
  },
  focusDar: {
    focus: '',
    data: '',
    action: '',
    response: '',
  },
  narrativeRecord: {
    narrativeNote: '',
  },
  remarks: {
    cbe: '',
  },
};

export const initialHospitalizationSurvey = {
  offer: '',
  contacts: [
    {
      contact: '',
      name: '',
      relation: '',
    },
    {
      contact: '',
      name: '',
      relation: '',
    },
    {
      contact: '',
      name: '',
      relation: '',
    },
  ],
  disease_history: {
    history: '',
    operation_history: '',
    latest_medicine: '',
    family_history: '',
    medicine_allergy: '',
    allergy: '',
    food_allergy: '',
  },
  body_status: {
    cycle: '',
    breath: '',
    camouflage: '',
    nerve: '',
    skin: '',
    operation_history: '',
    medicine_history: '',
    fall: '',
    yukchang: '',
    fain: '',
  },
  habit: {
    feces: '',
    feces_info: '',
    urine: '',
    urine_info: '',
    drink: '',
    smoke: '',
    sleep: '',
    nutrition: '',
    obstetric: '',
  },
  functional_evaluation: {
    sit: '',
    stand_up: '',
    wheel_chair: '',
    walk: '',
  },
  social_history: {
    marry: '',
    language: '',
    job: '',
    religion: '',
  },
  economy_history: {
    counseling: '',
    mind_status: '',
  },
  education: {
    education_way: '',
    education_contents: '',
  },
  out_hospital_plan: {
    life: '',
    guardian: '',
    destination: '',
  },
  default_info: {
    hospitalization_path: '',
    hospitalization_way: '',
    status: '',
    joo_ho_so: '',
    date: '',
    hospitalization_reason: '',
    height: '',
    weight: '',
    status02: '',
    SBP: '',
    DBP: '',
    PR: '',
    RR: '',
    BT: '',
    Sp02: '',
  },
};
